server:
  address: 0.0.0.0
  port: 8080
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://121.36.218.207/project_db?characterEncoding=utf-8&useSSL=false
    username: project_db
    password: gzyq2023
  mail:
    host: smtp.qq.com
    port: 587
    username: 2637927098@qq.com
    password: jfmyouluctveeaji
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    from: 2637927098@qq.com
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  #热部署
  devtools:
    restart:
      enabled: true
  freemarker:
    cache: false    #页面不加载缓存，修改即时生效
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.216:3306/yyk_db?characterEncoding=utf-8
    username: root
    password: gzyq2023
aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tQNWefomvBDfCiVt4Es
    access-key-secret: c8TFGQX0TD1SlqHLVG770VjQ98v4tB
    bucket-name: hgylyc

#mybatis plus配置
mybatis-plus:
  classpath: /mapper/*Mapper.xml
  mapper-locations: classpath*:mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.gem.entity
  global-config:
    #    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 0
    #    #驼峰下划线转换
    db-column-underline: true
    #    #mp2.3+ 全局表前缀 mp_
    table-prefix: mp_
    #    #刷新mapper 调试神器
    refresh-mapper: true
    #    #数据库大写下划线转换
    capital-mode: true
    #    # Sequence序列接口实现类配置
    key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
    #    #逻辑删除配置（下面3个配置）
    logic-delete-value: 1
    logic-not-delete-value: 0
  sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  #    #自定义填充策略接口实现
  meta-object-handler: com.baomidou.springboot.MyMetaObjectHandler
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: true
#    #配置JdbcTypeForNull, oracle数据库必须配置
#    jdbc-type-for-null: 'null'

