server:
  address: 0.0.0.0
  port: 8080
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://121.36.218.207/project_db?characterEncoding=utf-8&useSSL=false
    username: project_db
    password: gzyq2023
  mail:
    host: smtp.qq.com
    port: 587
    username: 2637927098@qq.com
    password: jfmyouluctveeaji
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    from: 2637927098@qq.com
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  #热部署
  devtools:
    restart:
      enabled: true
  freemarker:
    cache: false    #页面不加载缓存，修改即时生效
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.216:3306/yyk_db?characterEncoding=utf-8
    username: root
    password: gzyq2023



